### ISSUE TITLE
  Package spekulatius/spatie-crawler-toolkit-for-laravel has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  

### ISSUE THREAD

**Issue by MaxSangster** [spekulatius/spatie-crawler-toolkit-for-laravel#6]
I'm running composer 2.0.8 with PHP 8.0.0. What is incompatible with this module?

**Comment by spekulatius** [comment]
Good question, I haven't tested it (hence I left it out). I wouldn't know which part should be incompatible. If you want you could install it using the flag `--ignore-platform-reqs` and test it.

**Comment by spekulatius** [comment]
Hey @MaxSangster 

I've allowed PHP 8. As far as I know it should work. Let me know if you find any issues.

Cheers,
Peter
