### ISSUE TITLE
laravel 9 support

### ISSUE THREAD

**Issue by henzeb** [spekulatius/spatie-crawler-toolkit-for-laravel#9]
Atm there is no laravel 9 support. 

Problem 1
    - Root composer.json requires spekulatius/spatie-crawler-toolkit-for-laravel ^0.4.0 -> satisfiable by spekulatius/spatie-crawler-toolkit-for-laravel[0.4.0].
    - spekulatius/spatie-crawler-toolkit-for-laravel 0.4.0 requires laravel/framework ^6.0|^7.0|^8.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.2).

**Comment by spekulatius** [comment]
Hello @henzeb,

Are you interested in supporting the package with Laravel 9 support? You could fork it, adjust composer.json and check if / where the issues with Laravel 9 are.

Cheers,
Peter

**Comment by henzeb** [comment]
Just did, I tested the queue, haven't tested the events yet, but It looks like it works like a charm. 

The only thing is that ?$ttl requires you to add null to the constructor. Your readme may make it look like you don't need to.

https://github.com/henzeb/spatie-crawler-toolkit-for-laravel/tree/laravel-9

**Comment by spekulatius** [comment]
Fixed, please let me know if any issues come up :+1:
